name: ai_audiobook_platform
description: 听书 AI - iOS 小说实时配音 App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.0
  path_provider: ^2.1.5
  path: ^1.9.0
  crypto: ^3.0.6
  charset_converter: ^2.2.0
  charset: ^2.0.1
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
